;; Emacs configuration

;; Set convenient shortcuts to enter greek letters

(bind-key "M-g a" "α")
(bind-key "M-g b" "β")
(bind-key "M-g g" "γ")
(bind-key "M-g d" "δ")
(bind-key "M-g e" "ε")
(bind-key "M-g z" "ζ")
(bind-key "M-g h" "η")
(bind-key "M-g q" "θ")
(bind-key "M-g i" "ι")
(bind-key "M-g k" "κ")
(bind-key "M-g l" "λ")
(bind-key "M-g m" "μ")
(bind-key "M-g n" "ν")
(bind-key "M-g x" "ξ")
(bind-key "M-g o" "ο")
(bind-key "M-g p" "π")
(bind-key "M-g r" "ρ")
(bind-key "M-g s" "σ")
(bind-key "M-g t" "τ")
(bind-key "M-g u" "υ")
(bind-key "M-g f" "ϕ")
(bind-key "M-g j" "φ")
(bind-key "M-g c" "χ")
(bind-key "M-g y" "ψ")
(bind-key "M-g w" "ω")
(bind-key "M-g A" "Α")
(bind-key "M-g B" "Β")
(bind-key "M-g G" "Γ")
(bind-key "M-g D" "Δ")
(bind-key "M-g E" "Ε")
(bind-key "M-g Z" "Ζ")
(bind-key "M-g H" "Η")
(bind-key "M-g Q" "Θ")
(bind-key "M-g I" "Ι")
(bind-key "M-g K" "Κ")
(bind-key "M-g L" "Λ")
(bind-key "M-g M" "Μ")
(bind-key "M-g N" "Ν")
(bind-key "M-g X" "Ξ")
(bind-key "M-g O" "Ο")
(bind-key "M-g P" "Π")
(bind-key "M-g R" "Ρ")
(bind-key "M-g S" "Σ")
(bind-key "M-g T" "Τ")
(bind-key "M-g U" "Υ")
(bind-key "M-g F" "Φ")
(bind-key "M-g J" "Φ")
(bind-key "M-g C" "Χ")
(bind-key "M-g Y" "Ψ")
(bind-key "M-g W" "Ω")


